### ISSUE TITLE
[PTR] Energy Twister simulation miscalculation? 

### ISSUE THREAD

**Issue by matthewpetch** [d07RiV/d3planner#2]
Hi,

Just put by build into the planner and the simulation damage seems to be incorrect. 

I'm running the Energy Twister build for Wizard, so most of my damage should be coming from ET since DMO 6pc buffs the damage 2000%. However, in the simulation, it's calculating 52% of my damage is from Disintegrate - which isn't getting the 2000% multiplier, and is simply used to cast ET via the Etched Sigil affix. 

Link: http://ptr.d3planner.com/244913228

In the uptimes there are

Energy Twister
297.79%
energytwister
0.20%

Not sure if this is where the problem lies, but it does seem odd how the second isn't capitalised/spaced.

**Comment by d07RiV** [comment]
Fixed, but you also have an unfinished condition on that Slow Time so its never used.

**Comment by matthewpetch** [comment]
Oops, must have misclicked when I chose it.

Is the website version up to date? Still getting similar results, even with Slow Time working

**Comment by d07RiV** [comment]
It might still be cached on your end, it works for me now, at 249B DPS.
